version: '3.9'

services:
  web:
    image: 480041945529.dkr.ecr.us-east-2.amazonaws.com/${repo}:${tag}
    ports:
      - "8080:80"
    env_file:
      - /home/ubuntu/LoanPortal/LoanPortal.API/.env   # Mounted .env file from app server
    environment:
      # Only keep multi-line variable directly
       FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIKrgX55ysXJ9V\nbD3UL4/OjSD8rSyH3q9A29hB3jiAYDkItozQ9WVRyFO9cn0pImtWjSH149tmWGGN\nVLDgepBpG8wReL0wtPQFThQ6jB51cjzJiTSzXuLg47cXzK61f2Q51/NIbOsyIhdN\n70YA5xYsRWYUE0iWMsS4j5xNx8r3v0Itlz5Wn6ItxZwcrPW3m7r6zL/r0EJAdDBk\nGnBDAw3SQWtlNC3DkTNkg3N6BbRElFsGED7UrWi2kSux++gMBxgwJmX7gAlTOi59\nNLrmQg+PoTzgZH0KYDcToYJ04d+WR/1+QM5vIqRhxuhUL9p+rT/Wbfyts2StJ3qZ\n5tCCz9NnAgMBAAECggEAAumzF48bTJJBD1W/6bu3dJl4BpC8TJcFAnLnbZusjIiQ\ny+lgvYLd1ypDttjrGoD/cAcBLvEnEex/VcjmTFTXtAIosPGKk9kptjV69Lzfjb38\najAcZMtFRWGvh9iP1JfB/1fIBo5c7diyTPrl2VM6bs3s4TgyDIIUDjk7E1tDPysf\n30sl2Agcvd4eb5x5SJVkB8O75oL1fHtSzA7FqS+Bzra0ZTD/MyynqIrMRWiiUe1F\nPD4WaiQazBV9BBQ4ZU/XZCMP/KghLdOwSA8A22++YfMYsVsgTdMgzdwybKV31qzh\n5N8guYv194lBLbHQvULhJnCGXz07Er/IYqPZvixCgQKBgQD7q8+0BPkOKE8+lNnN\n3cSgFC551yDcspRBW2qMi9hFRF3QdF7E1lRTrNp93pLiBPXPTXNZK7If4lYXhwmS\nDFAKwAUcrLSEw3DHQGbHHTiK06xdsFMitC6tcJvmsBFZRQ01ZRgyVqnld/rvzeoV\nUDQY9j2CLECV2cjv0M2qHcV4UQKBgQDLnB40Vi/1Cvu6oZRVlSw49gUhvUFERC+U\ns+dp8F+C7038rNEp1uHsR8vdxuubuQ6WqmBdFfnOOTwp/Ofug0GGKHQ8CeTLNQ55\nZ6M4ABg3IHys6MrPa9Hi8tH+oRrJTuOBh8gpfTcS8zV2H1B3qb5ywRAMvsF8xRrT\nJYa3uI7aNwKBgE6+8ZxoOe1+G11/ga7yhwV3ixtAft3PWqggjHQxhZgWzivdXZHF\nZllQKoVb0SW7W5Zjq4XpMDDdxwZRkGMMSzcx4eeY+lrYND+EHSSMNhbqKHKgK0Me\nkcRfCcjiqmr+OiXM3gdSKpLMOc4y5d2JXOO6mIBUjFjW7hJriQ6DhjghAoGAO+Yh\nvKPeV+hzReRjDwpjiB5YRCS5Hqwwkz6ZxcDBWHOuLbdpkTV2IVy9zPDIP3ehoxFc\naAYfB1wvJusQEErs69ra1w7SEDX7nBuxGLhuZ0lXZEbX402E4Y8t2ArtJmve4ixf\n5lS/7wM9pxJvScTWEkxZvGYh5eLWkWdoyoOxAuECgYEAp20pb3McZDo1ZXBackrc\nl5LduX+8yR5NZ87wx9WkbSN3PZc67NLOsQrA1uuSPyWFukho8KqWO7B5VhokUkru\n5/Ov8unwH6sLCyO26nqOON9yXD1HROonmkgRnpZfOIWLOFS3otIvBwApNGOmUkCp\nvgk7eklnVodhHnIrsKqqdq8=\n-----END PRIVATE KEY-----\n"

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
