version: '3.9'

services:
  web:
    image: 480041945529.dkr.ecr.us-east-2.amazonaws.com/${repo}:${tag}
    ports:
      - "8080:80"
    environment:
      FIREBASE_TYPE: ${FIREBASE_TYPE}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_CLIENT_ID: ${FIREBASE_CLIENT_ID}
      FIREBASE_AUTH_URI: ${FIREBASE_AUTH_URI}
      FIREBASE_TOKEN_URI: ${FIREBASE_TOKEN_URI}
      FIREBASE_AUTH_PROVIDER_CERT_URL: ${FIREBASE_AUTH_PROVIDER_CERT_URL}
      FIREBASE_CLIENT_CERT_URL: ${FIREBASE_CLIENT_CERT_URL}
      AllowedOrigins: ${AllowedOrigins}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      MONGODB_USER_COLLECTION_NAME: ${MONGODB_USER_COLLECTION_NAME}
      MONGODB_PRE_APPROVAL_COLLECTION_NAME: ${MONGODB_PRE_APPROVAL_COLLECTION_NAME}
      FirebaseKey: ${FirebaseKey}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
