so we have everything right in payload ? although can you please verify once using below docker-compose for reference
version: '3.9'

services:
  web:
    image: 480041945529.dkr.ecr.us-east-2.amazonaws.com/${repo}:${tag}
    ports:
      - "8080:80"
    environment:
      FIREBASE_TYPE: ${FIREBASE_TYPE}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_CLIENT_ID: ${FIREBASE_CLIENT_ID}
      FIREBASE_AUTH_URI: ${FIREBASE_AUTH_URI}
      FIREBASE_TOKEN_URI: ${FIREBASE_TOKEN_URI}
      FIREBASE_AUTH_PROVIDER_CERT_URL: ${FIREBASE_AUTH_PROVIDER_CERT_URL}
      FIREBASE_CLIENT_CERT_URL: ${FIREBASE_CLIENT_CERT_URL}
      AllowedOrigins: ${AllowedOrigins}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      MONGODB_USER_COLLECTION_NAME: ${MONGODB_USER_COLLECTION_NAME}
      MONGODB_PRE_APPROVAL_COLLECTION_NAME: ${MONGODB_PRE_APPROVAL_COLLECTION_NAME}
      FirebaseKey: ${FirebaseKey}
      FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIKrgX55ysXJ9V\nbD3UL4/OjSD8rSyH3q9A29hB3jiAYDkItozQ9WVRyFO9cn0pImtWjSH149tmWGGN\nVLDgepBpG8wReL0wtPQFThQ6jB51cjzJiTSzXuLg47cXzK61f2Q51/NIbOsyIhdN\n70YA5xYsRWYUE0iWMsS4j5xNx8r3v0Itlz5Wn6ItxZwcrPW3m7r6zL/r0EJAdDBk\nGnBDAw3SQWtlNC3DkTNkg3N6BbRElFsGED7UrWi2kSux++gMBxgwJmX7gAlTOi59\nNLrmQg+PoTzgZH0KYDcToYJ04d+WR/1+QM5vIqRhxuhUL9p+rT/Wbfyts2StJ3qZ\n5tCCz9NnAgMBAAECggEAAumzF48bTJJBD1W/6bu3dJl4BpC8TJcFAnLnbZusjIiQ\ny+lgvYLd1ypDttjrGoD/cAcBLvEnEex/VcjmTFTXtAIosPGKk9kptjV69Lzfjb38\najAcZMtFRWGvh9iP1JfB/1fIBo5c7diyTPrl2VM6bs3s4TgyDIIUDjk7E1tDPysf\n30sl2Agcvd4eb5x5SJVkB8O75oL1fHtSzA7FqS+Bzra0ZTD/MyynqIrMRWiiUe1F\nPD4WaiQazBV9BBQ4ZU/XZCMP/KghLdOwSA8A22++YfMYsVsgTdMgzdwybKV31qzh\n5N8guYv194lBLbHQvULhJnCGXz07Er/IYqPZvixCgQKBgQD7q8+0BPkOKE8+lNnN\n3cSgFC551yDcspRBW2qMi9hFRF3QdF7E1lRTrNp93pLiBPXPTXNZK7If4lYXhwmS\nDFAKwAUcrLSEw3DHQGbHHTiK06xdsFMitC6tcJvmsBFZRQ01ZRgyVqnld/rvzeoV\nUDQY9j2CLECV2cjv0M2qHcV4UQKBgQDLnB40Vi/1Cvu6oZRVlSw49gUhvUFELCyO26nqOON9yXD1HROonmkgRnpZfOIWLOFS3otIvBwApNGOmUkCp\nvgk7eklnVodhHnIrsKqqdq8=\n-----END PRIVATE KEY-----\n"

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
