using MongoDB.Bson.Serialization.Attributes;
using LoanPortal.Shared.Enum;
using System;
using System.Collections.Generic;

namespace LoanPortal.Core.Entities
{
    // ─────────────────────────────────────────────────────────────────────────
    // MongoDB Documents
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Stored in the "BorrowerLinks" collection.
    /// One document per invite link generated by a Loan Officer.
    /// </summary>
    [BsonIgnoreExtraElements]
    public class BorrowerLinkDocument
    {
        [BsonId]
        public Guid Id { get; set; }

        /// <summary>MongoDB UserId of the Loan Officer who created the link.</summary>
        [BsonElement("loanOfficerId")]
        public Guid LoanOfficerId { get; set; }

        /// <summary>
        /// SHA-256 hex digest of the raw URL token.
        /// The raw token is NEVER stored — only this hash.
        /// </summary>
        [BsonElement("tokenHash")]
        public string TokenHash { get; set; }

        [BsonElement("status")]
        public BorrowerLinkStatus Status { get; set; }

        /// <summary>Optional borrower email hint pre-filled by the LO.</summary>
        [BsonElement("borrowerEmailHint")]
        public string? BorrowerEmailHint { get; set; }

        /// <summary>
        /// Firebase UID of the borrower — set on their first SaveDraft call.
        /// Ensures the same person resumes the draft.
        /// </summary>
        [BsonElement("borrowerFirebaseUid")]
        public string? BorrowerFirebaseUid { get; set; }

        /// <summary>Populated after borrower submits (links to the new PreApproval).</summary>
        [BsonElement("preApprovalId")]
        public Guid? PreApprovalId { get; set; }

        /// <summary>Link expires 30 days after creation.</summary>
        [BsonElement("expiresAt")]
        public DateTime ExpiresAt { get; set; }

        [BsonElement("createdAt")]
        public DateTime CreatedAt { get; set; }

        [BsonElement("updatedAt")]
        public DateTime UpdatedAt { get; set; }
    }

    /// <summary>
    /// Stored in the "BorrowerEmploymentDocuments" collection.
    /// One document per borrower link — holds draft progress and final submission.
    /// Keyed by LinkId; PreApprovalId is populated on final submit.
    /// </summary>
    [BsonIgnoreExtraElements]
    public class BorrowerEmploymentDocument
    {
        [BsonId]
        public Guid Id { get; set; }

        /// <summary>FK → BorrowerLinks._id</summary>
        [BsonElement("linkId")]
        public Guid LinkId { get; set; }

        /// <summary>FK → PreApprovals._id — set on final submit.</summary>
        [BsonElement("preApprovalId")]
        public Guid? PreApprovalId { get; set; }

        /// <summary>Last step the borrower fully completed (0 = not started, 1–9 = step completed).</summary>
        [BsonElement("lastCompletedStep")]
        public int LastCompletedStep { get; set; }

        [BsonElement("isSubmitted")]
        public bool IsSubmitted { get; set; }

        // ── Step 2: Personal Info ─────────────────────────────────────────────
        [BsonElement("personalInfo")]
        public BorrowerPersonalInfoDTO? PersonalInfo { get; set; }

        // ── Step 3: Employment Category ───────────────────────────────────────
        [BsonElement("employmentCategory")]
        public EmploymentCategory? EmploymentCategory { get; set; }

        // ── Steps 4–5: Current Employer(s) — EmployedByCompany ───────────────
        /// <summary>Supports multiple employers to satisfy the 2-year employment history requirement.</summary>
        [BsonElement("currentEmployers")]
        public List<BorrowerEmployerDTO>? CurrentEmployers { get; set; }

        // ── Steps 6–7: Income & Additional Info — EmployedByCompany ──────────
        [BsonElement("incomeDetails")]
        public BorrowerIncomeInputDTO? IncomeDetails { get; set; }

        [BsonElement("additionalInfo")]
        public BorrowerAdditionalInfoDTO? AdditionalInfo { get; set; }

        // ── Steps 4–7: Self-Employment data (populated when category = SelfEmployed) ──
        [BsonElement("selfEmployment")]
        public BorrowerSelfEmploymentDTO? SelfEmployment { get; set; }

        // ── Steps 3–5: Military data (populated when category = Military) ─────
        [BsonElement("militaryService")]
        public BorrowerMilitaryServiceDTO? MilitaryService { get; set; }

        // ── Step 8 (Company/SE) / Step 5 (Military): Previous Employers ──────
        /// <summary>Required if employment history is less than 2 years.</summary>
        [BsonElement("previousEmployers")]
        public List<BorrowerEmployerDTO>? PreviousEmployers { get; set; }

        [BsonElement("createdAt")]
        public DateTime CreatedAt { get; set; }

        [BsonElement("updatedAt")]
        public DateTime UpdatedAt { get; set; }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Step-level Sub-DTOs (used inside BorrowerEmploymentDocument)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>Step 2 — Verify Identity.</summary>
    [BsonIgnoreExtraElements]
    public class BorrowerPersonalInfoDTO
    {
        [BsonElement("firstName")]
        public string? FirstName { get; set; }

        [BsonElement("lastName")]
        public string? LastName { get; set; }

        [BsonElement("dateOfBirth")]
        public DateTime? DateOfBirth { get; set; }

        /// <summary>Last 4 digits of SSN. Used by LO for identity verification only.</summary>
        [BsonElement("last4SSN")]
        public string? Last4SSN { get; set; }

        [BsonElement("loanType")]
        public LoanType? LoanType { get; set; }
    }

    /// <summary>
    /// Steps 4 and 5 — Current Employer Information + Contact.
    /// Same shape is reused for previous employers (Step 8).
    /// </summary>
    [BsonIgnoreExtraElements]
    public class BorrowerEmployerDTO
    {
        // Step 4 — Employer Information
        [BsonElement("employerName")]
        public string? EmployerName { get; set; }

        [BsonElement("jobTitle")]
        public string? JobTitle { get; set; }

        [BsonElement("employmentType")]
        public EmploymentType? EmploymentType { get; set; }

        [BsonElement("isCurrentlyWorking")]
        public bool IsCurrentlyWorking { get; set; }

        [BsonElement("startDate")]
        public DateTime? StartDate { get; set; }

        [BsonElement("endDate")]
        public DateTime? EndDate { get; set; }

        // Step 5 — Employer Contact & Address
        [BsonElement("workPhone")]
        public string? WorkPhone { get; set; }

        [BsonElement("phoneExtension")]
        public string? PhoneExtension { get; set; }

        [BsonElement("employerAddress")]
        public string? EmployerAddress { get; set; }

        /// <summary>Indicates this employer is the borrower's primary income source.</summary>
        [BsonElement("isPrimaryIncome")]
        public bool IsPrimaryIncome { get; set; }
    }

    /// <summary>Steps 6 — Income Details (Employed).</summary>
    [BsonIgnoreExtraElements]
    public class BorrowerIncomeInputDTO
    {
        /// <summary>true = Salary, false = Hourly.</summary>
        [BsonElement("isSalary")]
        public bool IsSalary { get; set; }

        [BsonElement("basePay")]
        public decimal? BasePay { get; set; }

        [BsonElement("basePayFrequency")]
        public PayFrequency? BasePayFrequency { get; set; }

        [BsonElement("bonusPay")]
        public decimal? BonusPay { get; set; }

        [BsonElement("bonusFrequency")]
        public PayFrequency? BonusFrequency { get; set; }

        [BsonElement("overtimePay")]
        public decimal? OvertimePay { get; set; }

        [BsonElement("overtimeFrequency")]
        public PayFrequency? OvertimeFrequency { get; set; }

        [BsonElement("commissionPay")]
        public decimal? CommissionPay { get; set; }

        [BsonElement("commissionFrequency")]
        public PayFrequency? CommissionFrequency { get; set; }

        [BsonElement("otherPay")]
        public decimal? OtherPay { get; set; }

        [BsonElement("otherFrequency")]
        public PayFrequency? OtherFrequency { get; set; }
    }

    /// <summary>Step 7 — Additional Information (Employed).</summary>
    [BsonIgnoreExtraElements]
    public class BorrowerAdditionalInfoDTO
    {
        [BsonElement("isSeasonalIncome")]
        public bool IsSeasonalIncome { get; set; }

        [BsonElement("isForeignIncome")]
        public bool IsForeignIncome { get; set; }

        [BsonElement("isFamilyMemberEmployee")]
        public bool IsFamilyMemberEmployee { get; set; }

        [BsonElement("additionalComments")]
        public string? AdditionalComments { get; set; }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Self-Employment DTOs (Steps 4–7 of the Self-Employed flow)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Top-level container for all self-employment data.
    /// Stored inside BorrowerEmploymentDocument.SelfEmployment.
    /// </summary>
    [BsonIgnoreExtraElements]
    public class BorrowerSelfEmploymentDTO
    {
        // Step 4 — Self-Employment Details
        [BsonElement("businessName")]
        public string? BusinessName { get; set; }

        [BsonElement("positionTitle")]
        public string? PositionTitle { get; set; }

        [BsonElement("isCurrentlyWorking")]
        public bool IsCurrentlyWorking { get; set; }

        [BsonElement("isPrimaryIncome")]
        public bool IsPrimaryIncome { get; set; }

        [BsonElement("startDate")]
        public DateTime? StartDate { get; set; }

        [BsonElement("endDate")]
        public DateTime? EndDate { get; set; }

        // Step 5 — Business Contact & Address
        [BsonElement("businessContact")]
        public SelfEmployedBusinessContactDTO? BusinessContact { get; set; }

        // Step 6 — Self-Employment Income Details
        [BsonElement("incomeDetails")]
        public SelfEmployedIncomeDTO? IncomeDetails { get; set; }

        // Step 7 — Additional Information (reuses the shared DTO — same fields as employed flow)
        [BsonElement("additionalInfo")]
        public BorrowerAdditionalInfoDTO? AdditionalInfo { get; set; }
    }

    /// <summary>Step 5 — Business Contact & Address.</summary>
    [BsonIgnoreExtraElements]
    public class SelfEmployedBusinessContactDTO
    {
        [BsonElement("workPhone")]
        public string? WorkPhone { get; set; }

        [BsonElement("phoneExtension")]
        public string? PhoneExtension { get; set; }

        [BsonElement("businessAddress")]
        public string? BusinessAddress { get; set; }

        [BsonElement("city")]
        public string? City { get; set; }

        [BsonElement("state")]
        public string? State { get; set; }

        [BsonElement("zip")]
        public string? Zip { get; set; }
    }

    /// <summary>Step 6 — Self-Employment Income Details.</summary>
    [BsonIgnoreExtraElements]
    public class SelfEmployedIncomeDTO
    {
        /// <summary>Ownership share threshold: &lt;25% or ≥25%.</summary>
        [BsonElement("ownershipShare")]
        public OwnershipShareType? OwnershipShare { get; set; }

        /// <summary>Business entity / tax filing type (S-Corp, LLC, etc.).</summary>
        [BsonElement("businessEntityType")]
        public BusinessEntityType? BusinessEntityType { get; set; }

        /// <summary>Monthly net income or loss reported by the business.</summary>
        [BsonElement("monthlyIncomeOrLoss")]
        public decimal? MonthlyIncomeOrLoss { get; set; }

        /// <summary>Preferred documentation type the borrower can provide.</summary>
        [BsonElement("documentationType")]
        public IncomeDocumentationType? DocumentationType { get; set; }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Military DTOs (Steps 3–5 of the Military flow)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Top-level container for all military employment data.
    /// Stored inside BorrowerEmploymentDocument.MilitaryService.
    /// </summary>
    [BsonIgnoreExtraElements]
    public class BorrowerMilitaryServiceDTO
    {
        // Step 3 — Military Service Details
        [BsonElement("branchOfService")]
        public MilitaryBranch? BranchOfService { get; set; }

        [BsonElement("status")]
        public MilitaryStatus? Status { get; set; }

        /// <summary>Rank and pay grade (e.g. "E-5 Petty Officer Second Class").</summary>
        [BsonElement("rankPayGrade")]
        public string? RankPayGrade { get; set; }

        /// <summary>Military Occupational Specialty (MOS) — optional.</summary>
        [BsonElement("militaryOccupationalSpecialty")]
        public string? MilitaryOccupationalSpecialty { get; set; }

        [BsonElement("startDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>Separation date — required when IsCurrentlyServing = false.</summary>
        [BsonElement("separationDate")]
        public DateTime? SeparationDate { get; set; }

        [BsonElement("isCurrentlyServing")]
        public bool IsCurrentlyServing { get; set; }

        // Step 4 — Military Income Details
        [BsonElement("incomeDetails")]
        public MilitaryIncomeDTO? IncomeDetails { get; set; }

        // Step 5 — Additional Details
        [BsonElement("additionalDetails")]
        public MilitaryAdditionalDetailsDTO? AdditionalDetails { get; set; }
    }

    /// <summary>Step 4 — Military Income Details.</summary>
    [BsonIgnoreExtraElements]
    public class MilitaryIncomeDTO
    {
        // Base Pay
        [BsonElement("monthlyBasePay")]
        public decimal? MonthlyBasePay { get; set; }

        [BsonElement("basePayFrequency")]
        public PayFrequency? BasePayFrequency { get; set; }

        // Allowances (all stored as monthly amounts)
        [BsonElement("bahAmount")]
        public decimal? BAHAmount { get; set; }          // Basic Allowance for Housing

        [BsonElement("basAmount")]
        public decimal? BASAmount { get; set; }          // Basic Allowance for Subsistence

        [BsonElement("vhaAmount")]
        public decimal? VHAAmount { get; set; }          // Variable Housing Allowance

        // Other Military Income (optional — checked + amount per line)
        [BsonElement("flightPayAmount")]
        public decimal? FlightPayAmount { get; set; }

        [BsonElement("hazardPayAmount")]
        public decimal? HazardPayAmount { get; set; }

        [BsonElement("specialPayAmount")]
        public decimal? SpecialPayAmount { get; set; }

        [BsonElement("otherPayAmount")]
        public decimal? OtherPayAmount { get; set; }
    }

    /// <summary>Step 5 — Additional Military Details.</summary>
    [BsonIgnoreExtraElements]
    public class MilitaryAdditionalDetailsDTO
    {
        [BsonElement("isPrimaryIncome")]
        public bool IsPrimaryIncome { get; set; }

        /// <summary>"I expect to remain in the military for at least 3 more years."</summary>
        [BsonElement("expectToRemain3Years")]
        public bool ExpectToRemain3Years { get; set; }

        // Tax-free / special pay flags
        [BsonElement("receivesTaxFreeCombatPay")]
        public bool ReceivesTaxFreeCombatPay { get; set; }

        [BsonElement("receivesDeploymentHostileFirePay")]
        public bool ReceivesDeploymentHostileFirePay { get; set; }

        [BsonElement("receivesSeparationRetirementPay")]
        public bool ReceivesSeparationRetirementPay { get; set; }

        [BsonElement("additionalNotes")]
        public string? AdditionalNotes { get; set; }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // API Request / Response DTOs
    // ─────────────────────────────────────────────────────────────────────────


    /// <summary>POST /borrowerlink/generate — Loan Officer request.</summary>
    public class GenerateBorrowerLinkRequest
    {
        /// <summary>Optional: pre-fill borrower email shown on the welcome screen.</summary>
        public string? BorrowerEmailHint { get; set; }
    }

    /// <summary>Response returned to the Loan Officer after link generation.</summary>
    public class GenerateBorrowerLinkResponse
    {
        public Guid LinkId { get; set; }
        public string SecureUrl { get; set; }
        public DateTime ExpiresAt { get; set; }
    }

    /// <summary>GET /borrowerportal/resolve — public endpoint response.</summary>
    public class ResolveBorrowerLinkResponse
    {
        public Guid LinkId { get; set; }
        public string LoanOfficerName { get; set; }
        public string? LoanOfficerPhone { get; set; }
        public string? LoanOfficerProfile { get; set; }
        public string? LoanOfficerJobTitle { get; set; }
        public string? LoanOfficerNMLS { get; set; }
        public BorrowerLinkStatus Status { get; set; }
        public int LastCompletedStep { get; set; }
        /// <summary>Full draft data so the borrower can resume exactly where they left off.</summary>
        public BorrowerEmploymentDocument? DraftData { get; set; }
    }

    /// <summary>POST /borrowerportal/savedraft — borrower auto-save request.</summary>
    public class SaveBorrowerDraftRequest
    {
        public Guid LinkId { get; set; }
        /// <summary>Step number just completed (1–9).</summary>
        public int CompletedStep { get; set; }
        public BorrowerEmploymentDocument StepData { get; set; }
    }

    /// <summary>POST /borrowerportal/submit — borrower final submission request.</summary>
    public class SubmitBorrowerEmploymentRequest
    {
        public Guid LinkId { get; set; }
        public BorrowerEmploymentDocument EmploymentData { get; set; }
    }

    /// <summary>Response returned to the borrower after successful submission.</summary>
    public class SubmitBorrowerEmploymentResponse
    {
        public Guid PreApprovalId { get; set; }
        public string Message { get; set; }
    }
}

